version: '3'
services:
  app:
    restart: always
    image: test:1
    logging:
      driver: "json-file"
      options:
        max-size: "3M"
        max-file: "3"
    environment:
      - TZ=Asia/Taipei

    ports:
      - 50051:50051
